language: node_js

before_script:
  - psql -c 'create database english_test;' -U postgres
  - psql -c "CREATE USER migrator WITH PASSWORD '123';" -U postgres

node_js:
  - "stable"
services:
  - postgresql
cache:
  directories:
    - node_modules
script:
  - yarn test
on:
  branch: master