language: node_js

before_script:
  - psql -c 'create database english_test;' -U postgres

node_js:
  - "stable"
services:
  - postgresql
cache:
  directories:
    - node_modules
script:
  - npm run test
on:
  branch: master